foreground #459a64
background #000000
selection_foreground #f5c442
selection_background #010c7b

cursor #868d96
cursor_text_color #feffff

active_border_color #f5c442
active_tab_background #f5c442

color0 #262626
color1 #cd0400
color2 #f5c442
color3 #f5c442
color4 #6a3fef
color5 #ea3d8d
color6 #3376f6
color7 #feffff
color8 #484747
color9 #cd0400
color10 #ebbc3f
color11 #f5c442
color12 #ed7b3a
color13 #ea3d8d
color14 #3376f6
color15 #fefefe
