-- USGC RETICLE for Neovim. Dark is the upstream palette (PN 5200-020, ported
-- from usgraphics/usgc-themes); dimmed lifts it off pure black; light keeps the
-- same hues on a HIGHK white ground (PN 5200-010). No italics anywhere: USGC
-- ships `no_italic` in every theme.
--
-- Hue roles: red errors, amber strings, orange literals, purple types,
-- pink keywords, blue functions, green text, gray punctuation and comments.

local M = {}

M.palettes = {
  dark = {
    bg = "#000000",
    bg_alt = "#0a0a0a",
    bg_hl = "#1a1a1a",
    surface = "#262626",
    border = "#484747",
    dim = "#484747",
    comment = "#6d6c6a",
    gray = "#999999",
    fg = "#459a64",
    fg_bright = "#feffff",
    red = "#cd0400",
    amber = "#f5c442",
    amber_dim = "#ebbc3f",
    orange = "#ed7b3a",
    purple = "#6a3fef",
    pink = "#ea3d8d",
    blue = "#3376f6",
    sel_bg = "#010c7b",
    sel_fg = "#f5c442",
    cursor = "#868d96",
    cursor_fg = "#feffff",
    add = "#459a64",
    change = "#3376f6",
    delete = "#cd0400",
    diff_add = "#062b16",
    diff_change = "#041d3f",
    diff_delete = "#2a0604",
    diff_text = "#0b4a25",
    terminal = {
      "#262626",
      "#cd0400",
      "#f5c442",
      "#f5c442",
      "#6a3fef",
      "#ea3d8d",
      "#3376f6",
      "#feffff",
      "#484747",
      "#cd0400",
      "#ebbc3f",
      "#f5c442",
      "#ed7b3a",
      "#ea3d8d",
      "#3376f6",
      "#fefefe",
    },
  },
  dimmed = {
    bg = "#1c1c1c",
    bg_alt = "#232323",
    bg_hl = "#2a2a2a",
    surface = "#333333",
    border = "#454545",
    dim = "#565656",
    comment = "#8a8885",
    gray = "#a8a6a2",
    fg = "#6fa886",
    fg_bright = "#e6e6e4",
    red = "#d1524d",
    amber = "#d9b45f",
    amber_dim = "#c9a552",
    orange = "#d98a58",
    purple = "#8b6ef0",
    pink = "#dd6ba0",
    blue = "#5b8fe6",
    sel_bg = "#2a3560",
    sel_fg = "#d9b45f",
    cursor = "#9aa0a8",
    cursor_fg = "#1c1c1c",
    add = "#6fa886",
    change = "#5b8fe6",
    delete = "#d1524d",
    diff_add = "#17301f",
    diff_change = "#16213c",
    diff_delete = "#33191a",
    diff_text = "#1f4a2f",
    terminal = {
      "#333333",
      "#d1524d",
      "#d9b45f",
      "#d9b45f",
      "#8b6ef0",
      "#dd6ba0",
      "#5b8fe6",
      "#d8d8d6",
      "#565656",
      "#d1524d",
      "#c9a552",
      "#d9b45f",
      "#d98a58",
      "#dd6ba0",
      "#5b8fe6",
      "#e6e6e4",
    },
  },
  light = {
    bg = "#ffffff",
    bg_alt = "#f5f4f0",
    bg_hl = "#ecebe5",
    surface = "#dedcd5",
    border = "#c3c1ba",
    dim = "#b8b6b0",
    comment = "#6f6d68",
    gray = "#8f8d88",
    fg = "#0b6b39",
    fg_bright = "#000000",
    red = "#b30300",
    amber = "#8a6a00",
    amber_dim = "#7a5d00",
    orange = "#b4531a",
    purple = "#4b23c4",
    pink = "#b81f6a",
    blue = "#1f4fd0",
    sel_bg = "#d6dcf7",
    sel_fg = "#000000",
    cursor = "#0000ff",
    cursor_fg = "#ffffff",
    add = "#0b6b39",
    change = "#1f4fd0",
    delete = "#b30300",
    diff_add = "#e2f2e8",
    diff_change = "#e2e9fb",
    diff_delete = "#fbe4e2",
    diff_text = "#c8e6d4",
    terminal = {
      "#b8b6b0",
      "#b30300",
      "#8a6a00",
      "#8a6a00",
      "#4b23c4",
      "#b81f6a",
      "#1f4fd0",
      "#3f3f3d",
      "#8f8d88",
      "#b30300",
      "#7a5d00",
      "#8a6a00",
      "#b4531a",
      "#b81f6a",
      "#1f4fd0",
      "#000000",
    },
  },
}

local function highlights(p)
  return {
    -- Editor
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    NormalFloat = { fg = p.fg, bg = p.bg_alt },
    FloatBorder = { fg = p.border, bg = p.bg_alt },
    FloatTitle = { fg = p.amber, bg = p.bg_alt, bold = true },
    ColorColumn = { bg = p.bg_alt },
    Conceal = { fg = p.dim },
    Cursor = { fg = p.cursor_fg, bg = p.cursor },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    TermCursor = { link = "Cursor" },
    CursorLine = { bg = p.bg_hl },
    CursorColumn = { bg = p.bg_hl },
    CursorLineNr = { fg = p.amber, bold = true },
    LineNr = { fg = p.dim },
    LineNrAbove = { fg = p.dim },
    LineNrBelow = { fg = p.dim },
    SignColumn = { fg = p.dim, bg = p.bg },
    FoldColumn = { fg = p.dim, bg = p.bg },
    Folded = { fg = p.comment, bg = p.bg_alt },
    Directory = { fg = p.blue },
    EndOfBuffer = { fg = p.bg },
    NonText = { fg = p.dim },
    Whitespace = { fg = p.dim },
    SpecialKey = { fg = p.purple },
    MatchParen = { fg = p.amber, bg = p.surface, bold = true },
    Visual = { fg = p.sel_fg, bg = p.sel_bg },
    VisualNOS = { link = "Visual" },
    Search = { fg = p.bg, bg = p.amber_dim },
    IncSearch = { fg = p.bg, bg = p.orange },
    CurSearch = { fg = p.bg, bg = p.orange },
    Substitute = { fg = p.bg, bg = p.red },
    QuickFixLine = { bg = p.surface },
    WinSeparator = { fg = p.border, bg = p.bg },
    VertSplit = { link = "WinSeparator" },
    StatusLine = { fg = p.fg_bright, bg = p.surface },
    StatusLineNC = { fg = p.comment, bg = p.bg_alt },
    TabLine = { fg = p.comment, bg = p.surface },
    TabLineFill = { bg = p.bg_alt },
    TabLineSel = { fg = p.amber, bg = p.bg, bold = true },
    WinBar = { fg = p.comment, bg = p.bg },
    WinBarNC = { fg = p.dim, bg = p.bg },
    Title = { fg = p.amber, bold = true },
    MsgArea = { fg = p.fg },
    MsgSeparator = { fg = p.border },
    ModeMsg = { fg = p.fg_bright, bold = true },
    MoreMsg = { fg = p.blue },
    Question = { fg = p.blue },
    ErrorMsg = { fg = p.red, bold = true },
    WarningMsg = { fg = p.amber },
    Pmenu = { fg = p.fg, bg = p.bg_alt },
    PmenuSel = { fg = p.fg_bright, bg = p.surface, bold = true },
    PmenuKind = { fg = p.purple, bg = p.bg_alt },
    PmenuKindSel = { fg = p.purple, bg = p.surface },
    PmenuExtra = { fg = p.comment, bg = p.bg_alt },
    PmenuExtraSel = { fg = p.comment, bg = p.surface },
    PmenuMatch = { fg = p.amber, bg = p.bg_alt },
    PmenuMatchSel = { fg = p.amber, bg = p.surface, bold = true },
    PmenuSbar = { bg = p.bg_alt },
    PmenuThumb = { bg = p.border },
    WildMenu = { link = "PmenuSel" },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.amber, undercurl = true },
    SpellLocal = { sp = p.blue, undercurl = true },
    SpellRare = { sp = p.purple, undercurl = true },

    -- Syntax
    Comment = { fg = p.comment },
    Constant = { fg = p.purple },
    String = { fg = p.amber },
    Character = { fg = p.amber },
    Number = { fg = p.orange },
    Float = { fg = p.orange },
    Boolean = { fg = p.orange },
    Identifier = { fg = p.fg },
    Function = { fg = p.blue },
    Statement = { fg = p.pink },
    Conditional = { fg = p.pink },
    Repeat = { fg = p.pink },
    Label = { fg = p.pink },
    Exception = { fg = p.pink },
    Keyword = { fg = p.pink },
    Operator = { fg = p.fg_bright },
    PreProc = { fg = p.purple },
    Include = { fg = p.pink },
    Define = { fg = p.purple },
    Macro = { fg = p.purple },
    PreCondit = { fg = p.purple },
    Type = { fg = p.purple },
    StorageClass = { fg = p.purple },
    Structure = { fg = p.purple },
    Typedef = { fg = p.purple },
    Special = { fg = p.orange },
    SpecialChar = { fg = p.orange },
    Tag = { fg = p.pink },
    Delimiter = { fg = p.gray },
    SpecialComment = { fg = p.blue },
    Debug = { fg = p.red },
    Underlined = { underline = true },
    Ignore = { fg = p.dim },
    Error = { fg = p.red, bold = true },
    Todo = { fg = p.bg, bg = p.amber, bold = true },
    Added = { fg = p.add },
    Changed = { fg = p.change },
    Removed = { fg = p.delete },

    -- Diff
    DiffAdd = { bg = p.diff_add },
    DiffChange = { bg = p.diff_change },
    DiffDelete = { fg = p.delete, bg = p.diff_delete },
    DiffText = { bg = p.diff_text, bold = true },

    -- Diagnostics
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.amber },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.purple },
    DiagnosticOk = { fg = p.add },
    DiagnosticVirtualTextError = { fg = p.red },
    DiagnosticVirtualTextWarn = { fg = p.amber },
    DiagnosticVirtualTextInfo = { fg = p.blue },
    DiagnosticVirtualTextHint = { fg = p.purple },
    DiagnosticVirtualTextOk = { fg = p.add },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.amber, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.purple, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.add, undercurl = true },
    DiagnosticUnnecessary = { fg = p.dim },
    DiagnosticDeprecated = { fg = p.comment, strikethrough = true },

    -- LSP
    LspReferenceText = { bg = p.surface },
    LspReferenceRead = { bg = p.surface },
    LspReferenceWrite = { bg = p.surface, underline = true },
    LspInlayHint = { fg = p.dim, bg = p.bg_alt },
    LspSignatureActiveParameter = { fg = p.amber, bold = true },
    LspCodeLens = { fg = p.comment },
    LspInfoBorder = { fg = p.border, bg = p.bg_alt },
    ["@lsp.type.comment"] = {},

    -- Treesitter
    ["@variable"] = { fg = p.fg },
    ["@variable.builtin"] = { fg = p.red },
    ["@variable.parameter"] = { fg = p.fg_bright },
    ["@variable.member"] = { fg = p.fg },
    ["@constant"] = { fg = p.purple },
    ["@constant.builtin"] = { fg = p.orange },
    ["@constant.macro"] = { fg = p.purple },
    ["@module"] = { fg = p.fg_bright },
    ["@label"] = { fg = p.pink },
    ["@string"] = { fg = p.amber },
    ["@string.regexp"] = { fg = p.orange },
    ["@string.escape"] = { fg = p.orange },
    ["@string.special"] = { fg = p.orange },
    ["@string.special.url"] = { fg = p.blue, underline = true },
    ["@character"] = { fg = p.amber },
    ["@character.special"] = { fg = p.orange },
    ["@boolean"] = { fg = p.orange },
    ["@number"] = { fg = p.orange },
    ["@number.float"] = { fg = p.orange },
    ["@type"] = { fg = p.purple },
    ["@type.builtin"] = { fg = p.purple },
    ["@type.definition"] = { fg = p.purple },
    ["@attribute"] = { fg = p.blue },
    ["@property"] = { fg = p.fg },
    ["@function"] = { fg = p.blue },
    ["@function.builtin"] = { fg = p.blue },
    ["@function.call"] = { fg = p.blue },
    ["@function.macro"] = { fg = p.purple },
    ["@function.method"] = { fg = p.blue },
    ["@function.method.call"] = { fg = p.blue },
    ["@constructor"] = { fg = p.purple },
    ["@operator"] = { fg = p.fg_bright },
    ["@keyword"] = { fg = p.pink },
    ["@keyword.function"] = { fg = p.pink },
    ["@keyword.operator"] = { fg = p.pink },
    ["@keyword.import"] = { fg = p.pink },
    ["@keyword.return"] = { fg = p.pink },
    ["@keyword.exception"] = { fg = p.pink },
    ["@punctuation.delimiter"] = { fg = p.gray },
    ["@punctuation.bracket"] = { fg = p.gray },
    ["@punctuation.special"] = { fg = p.orange },
    ["@comment"] = { fg = p.comment },
    ["@comment.error"] = { fg = p.bg, bg = p.red, bold = true },
    ["@comment.warning"] = { fg = p.bg, bg = p.amber, bold = true },
    ["@comment.todo"] = { fg = p.bg, bg = p.blue, bold = true },
    ["@comment.note"] = { fg = p.bg, bg = p.purple, bold = true },
    ["@tag"] = { fg = p.pink },
    ["@tag.builtin"] = { fg = p.pink },
    ["@tag.attribute"] = { fg = p.blue },
    ["@tag.delimiter"] = { fg = p.gray },
    ["@markup.heading"] = { fg = p.amber, bold = true },
    ["@markup.heading.1"] = { fg = p.amber, bold = true },
    ["@markup.heading.2"] = { fg = p.orange, bold = true },
    ["@markup.heading.3"] = { fg = p.blue, bold = true },
    ["@markup.heading.4"] = { fg = p.purple, bold = true },
    ["@markup.heading.5"] = { fg = p.pink, bold = true },
    ["@markup.heading.6"] = { fg = p.fg_bright, bold = true },
    ["@markup.strong"] = { fg = p.fg_bright, bold = true },
    ["@markup.italic"] = { fg = p.fg_bright },
    ["@markup.strikethrough"] = { fg = p.comment, strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.raw"] = { fg = p.amber },
    ["@markup.quote"] = { fg = p.comment },
    ["@markup.math"] = { fg = p.purple },
    ["@markup.link"] = { fg = p.blue },
    ["@markup.link.label"] = { fg = p.pink },
    ["@markup.link.url"] = { fg = p.blue, underline = true },
    ["@markup.list"] = { fg = p.pink },
    ["@markup.list.checked"] = { fg = p.add },
    ["@markup.list.unchecked"] = { fg = p.dim },
    ["@diff.plus"] = { fg = p.add },
    ["@diff.minus"] = { fg = p.delete },
    ["@diff.delta"] = { fg = p.change },

    -- gitsigns
    GitSignsAdd = { fg = p.add },
    GitSignsChange = { fg = p.change },
    GitSignsDelete = { fg = p.delete },
    GitSignsCurrentLineBlame = { fg = p.dim },

    -- blink.cmp
    BlinkCmpMenu = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpMenuBorder = { fg = p.border, bg = p.bg_alt },
    BlinkCmpMenuSelection = { fg = p.fg_bright, bg = p.surface, bold = true },
    BlinkCmpLabelMatch = { fg = p.amber, bold = true },
    BlinkCmpLabelDeprecated = { fg = p.comment, strikethrough = true },
    BlinkCmpLabelDetail = { fg = p.comment },
    BlinkCmpLabelDescription = { fg = p.comment },
    BlinkCmpKind = { fg = p.purple },
    BlinkCmpDoc = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpDocBorder = { fg = p.border, bg = p.bg_alt },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = p.bg_alt },
    BlinkCmpSignatureHelpActiveParameter = { fg = p.amber, bold = true },
    BlinkCmpGhostText = { fg = p.dim },

    -- snacks
    SnacksNormal = { fg = p.fg, bg = p.bg_alt },
    SnacksWinBar = { fg = p.amber, bg = p.bg_alt, bold = true },
    SnacksBackdrop = { bg = p.bg },
    SnacksIndent = { fg = p.surface },
    SnacksIndentScope = { fg = p.border },
    SnacksDashboardHeader = { fg = p.amber },
    SnacksDashboardIcon = { fg = p.blue },
    SnacksDashboardKey = { fg = p.pink },
    SnacksDashboardDesc = { fg = p.fg },
    SnacksDashboardFooter = { fg = p.comment },
    SnacksPicker = { fg = p.fg, bg = p.bg_alt },
    SnacksPickerBorder = { fg = p.border, bg = p.bg_alt },
    SnacksPickerTitle = { fg = p.amber, bg = p.bg_alt, bold = true },
    SnacksPickerMatch = { fg = p.amber, bold = true },
    SnacksPickerDir = { fg = p.comment },
    SnacksPickerPathHidden = { fg = p.dim },
    SnacksPickerCursorLine = { bg = p.surface },
    SnacksNotifierInfo = { fg = p.blue, bg = p.bg_alt },
    SnacksNotifierWarn = { fg = p.amber, bg = p.bg_alt },
    SnacksNotifierError = { fg = p.red, bg = p.bg_alt },
    SnacksNotifierDebug = { fg = p.comment, bg = p.bg_alt },
    SnacksNotifierTrace = { fg = p.purple, bg = p.bg_alt },

    -- flash, which-key, trouble, noice, todo-comments, illuminate
    FlashLabel = { fg = p.bg, bg = p.pink, bold = true },
    FlashMatch = { fg = p.fg_bright, bg = p.surface },
    FlashCurrent = { fg = p.bg, bg = p.orange },
    WhichKey = { fg = p.pink },
    WhichKeyGroup = { fg = p.blue },
    WhichKeyDesc = { fg = p.fg },
    WhichKeySeparator = { fg = p.dim },
    WhichKeyValue = { fg = p.comment },
    WhichKeyNormal = { fg = p.fg, bg = p.bg_alt },
    WhichKeyBorder = { fg = p.border, bg = p.bg_alt },
    TroubleNormal = { fg = p.fg, bg = p.bg_alt },
    TroubleText = { fg = p.fg },
    TroubleCount = { fg = p.amber, bg = p.surface },
    NoiceCmdlinePopup = { fg = p.fg, bg = p.bg_alt },
    NoiceCmdlinePopupBorder = { fg = p.border, bg = p.bg_alt },
    NoiceCmdlineIcon = { fg = p.amber },
    NoiceConfirmBorder = { fg = p.border, bg = p.bg_alt },
    IlluminatedWordText = { bg = p.surface },
    IlluminatedWordRead = { bg = p.surface },
    IlluminatedWordWrite = { bg = p.surface, underline = true },
  }
end

-- `name` must equal the colors/ file that called us so that a later
-- `:set background` re-sources the same entrypoint instead of a stale one.
-- On a dark terminal `vim.g.usgc_reticle_dark` picks "dark" or "dimmed".
function M.load(variant, name)
  if not variant then
    variant = vim.o.background == "light" and "light" or (vim.g.usgc_reticle_dark or "dark")
  end
  if not M.palettes[variant] then
    variant = "dark"
  end

  local p = M.palettes[variant]
  local background = variant == "light" and "light" or "dark"

  if vim.o.background ~= background then
    -- Clear colors_name first: Neovim re-sources the colorscheme on this set.
    vim.g.colors_name = nil
    vim.o.background = background
  end

  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.g.colors_name = name

  for group, spec in pairs(highlights(p)) do
    vim.api.nvim_set_hl(0, group, spec)
  end

  for i, color in ipairs(p.terminal) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

return M
