#!/usr/bin/env python3
"""Generate Reticle ports from one palette; --check audits without writing."""

import argparse
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
PALETTES = json.loads((HERE / "palettes.json").read_text())
OMP_ROLES = json.loads((HERE / "omp-roles.json").read_text())
NOTICE = "Generated by desktop/reticle/generate.py; edit palettes.json instead."
ANSI_NAMES = "black red green yellow blue magenta cyan white".split()

# ANSI colors retain their conventional meanings; syntax-only hues stay RGB.
for palette in PALETTES.values():
    palette.update(add=palette["green"], change=palette["blue"], delete=palette["red"])
    palette["terminal"] = [palette[key] for key in (
        "ansi_black", "red", "green", "amber", "blue", "pink", "cyan", "fg_bright",
        "comment", "red", "green", "amber", "blue", "pink", "cyan", "fg_bright",
    )]


def luminance(color):
    channels = [int(color[i : i + 2], 16) / 255 for i in (1, 3, 5)]
    return sum(
        weight * (c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4)
        for weight, c in zip((0.2126, 0.7152, 0.0722), channels)
    )


def contrast(fg, bg):
    low, high = sorted((luminance(fg), luminance(bg)))
    return (high + 0.05) / (low + 0.05)


def audit():
    """Check text on actual base, popup, selected, and diff surfaces."""
    failures = []
    for name, p in PALETTES.items():
        text = "fg fg_bright comment gray dim red green amber amber_dim orange purple pink blue cyan".split()
        backgrounds = "bg bg_alt bg_hl surface ui_sel diff_add diff_change diff_delete diff_text".split()
        pairs = [(fg, bg) for fg in text for bg in backgrounds]
        pairs += [("sel_fg", "sel_bg"), ("cursor_fg", "cursor")]
        for fg, bg in pairs:
            ratio = contrast(p[fg], p[bg])
            if ratio < 4.5:
                failures.append(f"{name}: {fg} on {bg}: {ratio:.2f}:1")
        for index, color in enumerate(p["terminal"]):
            if index != 0 and contrast(color, p["bg"]) < 4.5:
                failures.append(f"{name}: ANSI {index} below 4.5:1")
        assert p["terminal"][2] == p["green"] == p["add"]
        assert p["terminal"][3] == p["amber"]
        assert p["terminal"][4] == p["blue"] == p["change"]
        assert p["terminal"][1] == p["red"] == p["delete"]
        print(f"{name}: text {contrast(p['fg'], p['bg']):.2f}:1, "
              f"comments {contrast(p['comment'], p['bg']):.2f}:1")
    if failures:
        raise SystemExit("Contrast audit failed:\n" + "\n".join(failures))


def ghostty(p):
    settings = {
        "background": "bg", "foreground": "fg", "cursor-color": "cursor",
        "cursor-text": "cursor_fg", "selection-background": "sel_bg",
        "selection-foreground": "sel_fg",
    }
    lines = [f"# {NOTICE}", "# USGC-derived semantic TUI palette; see desktop/reticle/README.md."]
    lines += [f"{key} = {p[token]}" for key, token in settings.items()]
    lines += [""] + [f"palette = {i}={color}" for i, color in enumerate(p["terminal"])]
    return "\n".join(lines) + "\n"


def toml_sections(sections):
    lines = [f"# {NOTICE}"]
    for name, values in sections.items():
        lines += ["", f"[{name}]"]
        lines += [f'{key} = "{value}"' for key, value in values.items()]
    return "\n".join(lines) + "\n"


def alacritty(p):
    return toml_sections({
        "colors.primary": {"background": p["bg"], "foreground": p["fg"]},
        "colors.cursor": {"text": p["cursor_fg"], "cursor": p["cursor"]},
        "colors.vi_mode_cursor": {"text": p["cursor_fg"], "cursor": p["cursor"]},
        "colors.search.matches": {"foreground": p["bg"], "background": p["amber"]},
        "colors.search.focused_match": {"foreground": p["bg"], "background": p["red"]},
        "colors.footer_bar": {"foreground": p["bg"], "background": p["fg"]},
        "colors.selection": {"text": p["sel_fg"], "background": p["sel_bg"]},
        "colors.normal": dict(zip(ANSI_NAMES, p["terminal"][:8])),
        "colors.bright": dict(zip(ANSI_NAMES, p["terminal"][8:])),
    })


def foot(p):
    section = "colors-light" if p["mode"] == "light" else "colors"
    lines = [f"# {NOTICE}", f"[{section}]",
             f"foreground={p['fg'][1:]}", f"background={p['bg'][1:]}",
             f"selection-foreground={p['sel_fg'][1:]}",
             f"selection-background={p['sel_bg'][1:]}",
             f"cursor={p['cursor_fg'][1:]} {p['cursor'][1:]}", ""]
    lines += [f"regular{i}={color[1:]}" for i, color in enumerate(p["terminal"][:8])]
    lines += [f"bright{i}={color[1:]}" for i, color in enumerate(p["terminal"][8:])]
    return "\n".join(lines) + "\n"


def kitty(p):
    settings = {
        "foreground": "fg", "background": "bg", "selection_foreground": "sel_fg",
        "selection_background": "sel_bg", "cursor": "cursor", "cursor_text_color": "cursor_fg",
        "active_border_color": "amber", "active_tab_background": "amber",
        "active_tab_foreground": "bg", "inactive_tab_background": "bg_alt",
        "inactive_tab_foreground": "comment",
    }
    lines = [f"# {NOTICE}"] + [f"{key} {p[token]}" for key, token in settings.items()]
    lines += [""] + [f"color{i} {color}" for i, color in enumerate(p["terminal"])]
    return "\n".join(lines) + "\n"


def omarchy(p):
    settings = {
        "accent": "amber", "selection": "sel_bg", "muted": "comment",
        "background": "bg", "dark_background": "bg_hl", "darker_background": "surface",
        "lighter_background": "bg_alt", "foreground": "fg", "dark_foreground": "comment",
        "light_foreground": "gray", "bright_foreground": "fg_bright", "orange": "orange",
        "brown": "orange",
    }
    values = {"mode": p["mode"], **{key: p[token] for key, token in settings.items()}}
    values.update(zip(ANSI_NAMES, p["terminal"][:8]))
    values.update(zip(("bright_" + c for c in ANSI_NAMES), p["terminal"][8:]))
    return f"# {NOTICE}\n" + "\n".join(f'{k} = "{v}"' for k, v in values.items()) + "\n"


def lua(value, indent=0):
    if isinstance(value, str):
        return json.dumps(value)
    entries = value.items() if isinstance(value, dict) else enumerate(value)
    lines = ["{"]
    for key, item in entries:
        prefix = f"{key} = " if isinstance(value, dict) else ""
        lines.append(" " * (indent + 2) + prefix + lua(item, indent + 2) + ",")
    return "\n".join(lines) + "\n" + " " * indent + "}"


def helix(p):
    roles = {
        "attribute": "amber", "type": "purple", "constructor": "purple",
        "constant": "orange", "constant.builtin": "purple",
        "string": "fg", "string.regexp": "cyan", "string.special": "cyan",
        "comment": "comment", "variable": "fg", "variable.builtin": "purple",
        "variable.parameter": "fg", "punctuation": "gray", "operator": "pink",
        "keyword": "pink", "function": "blue", "tag": "pink", "namespace": "blue",
        "special": "amber", "markup.heading": "amber", "markup.list": "pink",
        "markup.link.url": "blue", "markup.link.text": "cyan",
        "markup.raw": "fg", "markup.quote": "comment",
        "diff.plus": "green", "diff.minus": "red", "diff.delta": "blue",
        "warning": "amber", "error": "red", "info": "blue", "hint": "cyan",
        "ui.linenr": "comment", "ui.linenr.selected": "amber",
        "ui.text.directory": "blue", "ui.text.inactive": "comment",
        "ui.virtual.indent-guide": "border", "ui.virtual.whitespace": "border",
        "ui.virtual.inlay-hint": "comment", "ui.virtual.jump-label": "amber",
    }
    lines = [f"# {NOTICE}"]
    lines += [f'"{scope}" = "{color}"' for scope, color in roles.items()]
    surfaces = {
        "ui.background": ("fg", "bg"), "ui.text": ("fg", "bg"),
        "ui.selection": ("fg", "ui_sel"), "ui.selection.primary": ("fg", "ui_sel"),
        "ui.cursor": ("cursor_fg", "cursor"), "ui.cursor.primary": ("cursor_fg", "cursor"),
        "ui.cursor.match": ("amber", "bg_hl"),
        "ui.statusline": ("fg", "bg_alt"), "ui.statusline.inactive": ("comment", "bg_alt"),
        "ui.statusline.normal": ("bg", "amber"), "ui.statusline.insert": ("bg", "green"),
        "ui.statusline.select": ("bg", "blue"),
        "ui.bufferline": ("comment", "bg_alt"), "ui.bufferline.active": ("amber", "surface"),
        "ui.bufferline.background": ("fg", "bg_alt"),
        "ui.popup": ("fg", "bg_alt"), "ui.popup.info": ("fg", "bg_alt"),
        "ui.help": ("fg", "bg_alt"), "ui.menu": ("fg", "bg_alt"),
        "ui.menu.selected": ("amber", "ui_sel"), "ui.text.focus": ("amber", "ui_sel"),
        "ui.text.info": ("fg", "bg_alt"), "ui.window": ("border", "bg"),
        "ui.highlight": ("fg", "ui_sel"), "ui.gutter": ("comment", "bg"),
    }
    lines += [f'"{scope}" = {{ fg = "{fg}", bg = "{bg}" }}' for scope, (fg, bg) in surfaces.items()]
    for kind, color in (("error", "red"), ("warning", "amber"), ("info", "blue"), ("hint", "cyan")):
        lines.append(f'"diagnostic.{kind}" = {{ underline = {{ color = "{color}", style = "curl" }} }}')
    lines += ['"markup.bold" = { modifiers = ["bold"] }',
              '"markup.italic" = { modifiers = ["italic"] }', "", "[palette]"]
    lines += [f'{key} = "{value}"' for key, value in p.items() if isinstance(value, str) and value.startswith("#")]
    return "\n".join(lines) + "\n"


def nushell(p):
    roles = {
        "separator": "border", "header": "amber", "row_index": "comment",
        "bool": "purple", "int": "orange", "float": "orange", "filesize": "orange",
        "duration": "orange", "date": "cyan", "range": "orange", "binary": "orange",
        "string": "fg", "nothing": "comment", "record": "fg", "list": "fg",
        "block": "fg", "closure": "fg", "cell-path": "blue",
        "hints": "comment", "search_result": "amber",
        "shape_and": "pink", "shape_binary": "orange", "shape_block": "blue",
        "shape_bool": "purple", "shape_closure": "blue", "shape_custom": "fg",
        "shape_datetime": "cyan", "shape_directory": "blue", "shape_external": "blue",
        "shape_externalarg": "fg", "shape_external_resolved": "blue",
        "shape_filepath": "blue", "shape_flag": "amber", "shape_float": "orange",
        "shape_garbage": "red", "shape_glob_interpolation": "cyan", "shape_globpattern": "cyan",
        "shape_int": "orange", "shape_internalcall": "blue", "shape_keyword": "pink",
        "shape_list": "fg", "shape_literal": "fg", "shape_match_pattern": "cyan",
        "shape_matching_brackets": "amber", "shape_nothing": "comment",
        "shape_operator": "pink", "shape_or": "pink", "shape_pipe": "pink",
        "shape_range": "orange", "shape_record": "fg", "shape_redirection": "pink",
        "shape_signature": "fg", "shape_string": "fg", "shape_string_interpolation": "cyan",
        "shape_table": "fg", "shape_variable": "fg", "shape_vardecl": "fg",
    }
    return json.dumps({key: p[color] for key, color in roles.items()}, indent=2) + "\n"


def herdr_theme():
    # Named colors follow the terminal palette; inactive tabs also apply DIM.
    # Bright neutral labels remain legible without adding a second dim color.
    lines = ["# BEGIN GENERATED RETICLE THEME", f"# {NOTICE}", "[theme]",
             'name = "terminal"', 'auto_switch = true', 'dark_name = "terminal"',
             'light_name = "catppuccin-latte"', "", "[theme.custom]"]
    roles = {"accent": "yellow", "text": "reset", "subtext0": "darkgray",
             "overlay0": "white", "overlay1": "white", "mauve": "magenta",
             "green": "green", "yellow": "yellow", "red": "red", "blue": "blue",
             "teal": "cyan", "peach": "yellow", "panel_bg": "reset", "sidebar_bg": "reset",
             "active_row_bg": "reset", "selection_bg": "reset",
             "surface0": "reset", "surface1": "reset", "surface_dim": "black"}
    lines += [f'{key} = "{color}"' for key, color in roles.items()]
    # Accent badges need a light foreground when the palette switches to light.
    lines += ["", "[theme.custom.light]",
              f'surface_dim = "{PALETTES["light"]["bg"]}"']
    return "\n".join(lines) + "\n# END GENERATED RETICLE THEME"


def outputs():
    result = {}
    for variant, p in PALETTES.items():
        name = p["name"]
        result[f"desktop/ghostty/themes/{name.upper()}-GH"] = ghostty(p)
        theme = {
            "$schema": "https://raw.githubusercontent.com/can1357/oh-my-pi/main/packages/coding-agent/src/modes/theme/theme-schema.json",
            "name": name,
            "vars": {key: value for key, value in p.items() if isinstance(value, str) and value.startswith("#")},
            "colors": OMP_ROLES,
            "export": {"pageBg": p["bg"], "cardBg": p["bg_alt"], "infoBg": p["ui_sel"]},
        }
        result[f"agents/omp/themes/{name}.json"] = json.dumps(theme, indent=2) + "\n"
        result[f"editors/helix/themes/{name}.toml"] = helix(p)
        result[f"shells/nu/themes/{name}.json"] = nushell(p)
        result[f"editors/nvim/colors/{name}.lua"] = f'require("reticle").load("{variant}", "{name}")\n'
        folder = f"desktop/omarchy/themes/{name}"
        for filename, render in (("ghostty.conf", ghostty), ("alacritty.toml", alacritty),
                                 ("foot.ini", foot), ("kitty.conf", kitty), ("colors.toml", omarchy)):
            result[f"{folder}/{filename}"] = render(p)
        result[f"{folder}/neovim.lua"] = (
            'return {\n  {\n    "LazyVim/LazyVim",\n    opts = {\n'
            f'      colorscheme = "{name}",\n    }}' + '\n  },\n}\n'
        )
        # Keep the existing icon family for both appearances.
        result[f"{folder}/icons.theme"] = (ROOT / "desktop/omarchy/themes/reticle-dark/icons.theme").read_text()
    result["editors/nvim/lua/reticle/palettes.lua"] = f"-- {NOTICE}\nreturn " + lua(PALETTES) + "\n"
    for name in ("cli/herdr/config.toml", "cli/herdr/config.omarchy.toml"):
        source = (ROOT / name).read_text()
        pattern = r"# BEGIN GENERATED RETICLE THEME.*?# END GENERATED RETICLE THEME"
        if len(re.findall(pattern, source, re.S)) != 1:
            raise SystemExit(f"Missing or duplicated theme markers in {name}")
        result[name] = re.sub(pattern, lambda _: herdr_theme(), source, flags=re.S)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    audit()
    stale = []
    generated = outputs()
    for name, content in generated.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Regenerate stale themes:\n" + "\n".join(stale))
    print(f"{'Checked' if args.check else 'Generated'} {len(generated)} theme files.")


if __name__ == "__main__":
    main()
