[bootstrap.packages]
"brew:chromaprint" = "latest"

[tools]
"pipx:beets" = { version = "latest", extras = "chroma,embedart,fetchart,lastgenre,lyrics" }

[dotfiles]
"~/.config/beets" = { source = "~/src/dotfiles/cli/beets", mode = "symlink-each" }
